.docker/images/govcms8/settings/development.services.yml
.docker/images/govcms8/settings/development.settings.php
.docker/images/govcms8/settings/settings.php
.env.default
docker-compose.yml

If a `DEV_MODE` flag is enabled in `.env` then default development settings will apply:
- No CSS/JS aggregation
- No GA tracking
- Verbose error logging
- Max cache age 0
- Null cache backend
A `development.services.yml` file will also be included:
- Twig debug enabled
- Twig cache disabled
- Twig autoload enabled
- http.response.debug_cacheability_headers enabled

Allow common dev environment settings via DEV_MODE flag

---

.docker/Dockerfile.govcms8
.docker/Dockerfile.php

Updates default max_input_vars to 2000 same as D7 PR -->
https://github.com/govCMS/govcmslagoon/pull/48

Added custom PHP_MAX_INPUT_VARS env var in code and cli images.

---

.docker/images/govcms8/settings/settings.php

Fix for private files and `fast_404` same as for D7 -- https://github.com/govCMS/govcmslagoon/pull/49

Ignore private files in fast 404.

---

.circleci/config.yml

There has been a change where `CIRCLE_BRANCH` is no longer set on tagged builds.
PR updates deployment conditions to deploy images on tagged builds.
https://github.com/govCMS/govCMS/pull/756

Deploy tagged images on tag builds.

---

.docker/images/govcms8/settings/production.settings.php

When enabling the google analytics module on a production account console errors are bing thrown. I've logged an internal ticket: #779

Updated settings from ga to gtag for drupal8

---

.docker/images/govcms8/settings/settings.php

Similar PR to https://github.com/govCMS/govcmslagoon/pull/56
Disables redis by default and can be reenabled by adding the ENABLE_REDIS to lagoon-env.
redis will be disabled on all sites by default

Added condition to enable redis config.

---

.docker/Dockerfile.nginx-drupal
.docker/images/nginx/x_frame_options.conf
.docker/images/nginx/x_frame_options.template
.env.default
docker-compose.yml

Provides support to individual projects allowing control over X-Frame-Options when embedding content elsewhere.
The default remains as `SAMEORIGIN`, and a change in `.env` alone is not enough to make the change occur. Seckit click-jacking will also need to be disabled, as it is installed with a default header value of `SAMEORIGIN` as well - so this needs to be configured to suit in cases where this is allowed.

Support overrides to X-Frame-Options in Nginx configuration.

---

.docker/images/govcms8/scripts/govcms-deploy

GOVCMSD8-145
An issue has been found which can lead to the data loss of GovCMS8 SaaS site.
Setup the local project from https://projects.govcms.gov.au/sandbox/waterrating 
Restore the database from databasebackup (Backup ID: 6d14a9e8e8e25ba9416122ba28ca5af020173fa39c0b77fcd1ca0cff1693fd7c)
Run
govcms-deploy
or 
drush cim -y sync && drush updb -y
The error message can be found from the output 
[warning] Update function webform_update_8151 not found
[error] Update failed: webform_update_8151 
After the investigation, this issue is caused by a bug in the PR https://github.com/govCMS/govcms8lagoon/pull/6 - Configuration import on deploy
And this line has a bug which can lead to data loss such as modules and themes uninstalled in certain circumstances
drush cim -y sync
Run a cache rebuild …

Clear cache before configuration import

---

.docker/Dockerfile.govcms8
.docker/Dockerfile.mariadb-drupal
.docker/Dockerfile.nginx-drupal
.docker/Dockerfile.php
.docker/Dockerfile.test

Update the version numbers of the govcms distribution for release v6.10.1.

Update version numbers for release v6.10.1

---

.circleci/config.yml

Adding a pair of steps to CircleCI to install a dummy site, then get a Drush status, and Drush pm:list to serve as a visual check that updates have applied properly.
(matches govcms/govcmslagoon#66)

Add a release/version check step into CircleCI for confirmation

---

.docker/images/govcms8/scripts/govcms-deploy

We need to improve the govcms_deploy process and add the cache rebuild process after distribution update.
Otherwise, the site can throw a 500 error.

[GOVCMSD8-169] Adding cache rebuild after distribution update

---

.docker/Dockerfile.govcms8

Search under certain configurations can produce a fatal error.
This is a temporary fix for https://github.com/govCMS/govCMS8/pull/256 until it is merged/released.

Temporary GA patch

---

.docker/Dockerfile.govcms8
.docker/Dockerfile.mariadb-drupal
.docker/Dockerfile.nginx-drupal
.docker/Dockerfile.php
.docker/Dockerfile.test

The last change didn't include semver's point release identifier.
This will remediate that and provide a more consistent identification convention.

Update version numbers to include point release indicators

---

.env.default

Updates the Drutiny test dependency used by the test container to `7.x-3.x-beta2`.

Update audit_site to 7.x-3.x latest HEAD

---

.docker/Dockerfile.govcms8
.docker/Dockerfile.test
tests/goss/goss.govcms8.yaml
tests/goss/goss.test.yaml

in https://github.com/govCMS/audit-site/issues/34 some tests were identified as relying on find options not supported in the OOTB version of find.
This PR adds the full GNU findutils package to restore this functionality - it also modifies the apk command to not leave a cache in the end product image
APK adds can be removed if/when https://github.com/amazeeio/lagoon/pull/1077 lands.

[GOVCMSD8-362] Add findutils to govcms8lagoon cli and test images

---

.docker/Dockerfile.php

- Drupal doesn't require GMP so this will remove the module from the container.

[GOVCMSD8-396] Remove the GMP module from PHP.

---

.docker/images/govcms8/scripts/govcms-deploy

- The database update was being triggered prior to the database backup being taken this could result in an broken database backup.

[GOVCMSD8-397] Re-enable predeploy database backups.

---

.docker/Dockerfile.chrome

Pinning to last good v74 chromedriver version (https://github.com/SeleniumHQ/docker-selenium/releases) as per https://medium.com/@alex.designworks/chromedriver-75-enforces-w3c-standard-breaking-behat-tests-460cad435545

hotfix selenium/standalone-chrome:3.141.59-oxygen

---

.docker/Dockerfile.govcms8

Added `COMPOSER_MEMORY_LIMIT` to prevent composer installation failures.
Ensure correct permissions on `settings.php`

Resolve composer memory limit issue, writable settings.php file

---

.circleci/config.yml
composer.json

* Using drush 8.2.3 for backup and restore
* Disable email notification during install and later (D8). If your server has no mail transfer agent, this gets rid of an error during install.

Downgrade drush to 8.2.3

---

.docker/images/govcms8/scripts/govcms-deploy

- Removes redundancy by moving common functionality to `common_setup`
- Fixes bug where database updates were not run after db sync on initial non-prod deployment
- Re-introduces explicit cache rebuild

[GOVCMSD8-421] Refactored and simplified deployment script.

---

.docker/Dockerfile.govcms8
.docker/Dockerfile.php

- Removes composer cache.
- Removes apk cache.
Using `composer clearcache` to remove the caches as this can clear caches in all the directories that composer is configured to use.
@see https://github.com/composer/composer/pull/3175/files

[GOVCMSD8-419] Remove caches from the container build.

---

tests/goss/goss.php.yaml

circleCI builds are failing, as clamav is taking >60secs to complete EICAR file scan.
This hotfix allows more time for the tests to complete.

Fix clamav timeout for tests

---

.docker/images/govcms8/scripts/govcms-deploy

At some point the version of Drush changed from 8.x to 9.x in the govcms8lagoon images.
The drush alias used for v8 was previously `govcms-prod`, however the alias built for v9 is `govcms.prod`.

[GOVCMS-3816] Changed prod drush alias.

---

.docker/Dockerfile.govcms8

Currently the govcms8 image build process does not allow the use of a previous composer.lock file to be provided. This means that a "rebuild" of a previous release will have different dependency resolution.
composer.lock files should not ordinarily be committed, but extracted from tagged releases (or re-used in the case of frequent daily builds)

[GOVCMSD8-437] Allow use of existing composer.lock file to rebuild previous version

---

.docker/Dockerfile.govcms8

with the carat not properly escaped, the sed fails, and composer pulls in the HEAD instead (which, when the webflo/drupal-core-strict is ahead of GovCMS, could result in dependency issues)

[GOVCMSD8-439] Escape carat in sed expression

---

.docker/Dockerfile.govcms8
composer.json

This is needed when installing from composer.lock.  The Drupal-scaffold process will be skipped if building from a lockfile (as it assumes there is already a drupal system in place).
This is not the case in our base images, and therefore we have to ensure that this process runs regardless.  I have created a composer script and call it in the govcms8 dockerfile.  In circumstances where we are not installing from lockfiles, the file creation process runs twice, but this has negligible affect on timing, and zero impact on images

[GOVCMSD8-438] Add in explicit drupal-scaffold command

---

.docker/images/govcms8/settings/settings.php

'0' was being treated as a falsey always so even with the correct environment variables set it would still use the binary.
- Adds a strict type check for `!== false` as getenv will return bool if the variable is not defined.
- Adds a looser catch by setting to a string of `daemon` so we can fallback if '0' is mistreated.

[GOVCMSD8-440] Update catch for CLAMAV_MODE.

---

.docker/images/govcms8/settings/production.settings.php
docker-compose.yml

Alters default max-age header to 1h with env var override.

Set default cache time to 1h.

---

.docker/images/govcms8/scripts/govcms-deploy
.docker/images/govcms8/settings/production.settings.php

Ensure database drop before sync.

Rolled back default max-age header to 900s.

---

.docker/Dockerfile.nginx-drupal
.docker/images/nginx/drupal/favicon.conf
.docker/images/nginx/helpers/230-favicon.conf
tests/goss/goss.nginx-drupal.yaml

Adds a nginx config value to redirect /favicon to one provided by the profile if it does not exist. This happens when loading files (PDFs) or server errors as the browser will request /favicon.ico by default.

[GOVCMS-3216]: Change default favicon location

---

.docker/Dockerfile.php
.docker/images/nginx/helpers/000-client_max_body.conf
.docker/images/php/00-govcms.ini
tests/goss/goss.nginx-drupal.yaml
tests/goss/goss.php.yaml

- Changes nginx max_client_size to 256m
- Changes php max upload size to 256m
- Add goss checking for configuration.

Update the max upload size to 256m.

---

tests/goss/goss.php.yaml

* Remove dependency on eicar.org uptime (many failures in past due to network connectivity issue)
* Alter test file + approach (piped output was not working)

Fix clamscan test

---

.docker/images/govcms8/settings/settings.php

Superseded variable names break functionality in current configuration.
This PR updates the variable name and adds the `pdf` extension to supported extensions.

[GOVCMSD8-433]: Update Fast404 configuration

---

composer.json

- Add the scaffold tooling repository to the base image. This will include the necessary deploy scripts to the images.

[GOVCMS-4391]: Add scaffold-tooling to the base image.

---

.circleci/config.yml
.docker/images/nginx/tests/bootstrap.php
.docker/images/nginx/tests/composer.json
.docker/images/nginx/tests/src/BlocksTest.php
.docker/images/nginx/tests/src/FilesCacheTest.php
.docker/images/nginx/tests/src/FrameOptionsTest.php
.docker/images/nginx/tests/src/PrivateFilesTest.php
.docker/images/nginx/tests/src/RobotsTagTest.php
.docker/images/nginx/tests/src/RobotsTxtTest.php
.docker/images/nginx/tests/src/SecurityHeadersTest.php
.gitlab-ci.yml

- Fixed `nginx` URL in tests to only use URI accessible within containers. 
**Note that this change is required to correctly handle newer versions of Docker Compose (which reads variables from .env) - this will be available to check in another PR when we update CI container image with new version of Docker and Docker Compose.**
- Updated PHPunit helpers to use verbose output when `--debug` is provided for tests.
- Fixed coding standards in all tests to follow Drupal coding standards.
- Updated CircleCI CI config to wait for `nginx` container and check for `composer.json` validity.
- Updated GitLab CI config to wait for `nginx` container and check for `composer.json` validity.
- Removed pushing of Docker images from CircleCI as this is now handled in GitLab.
Please see inline comments for …

Updated test helpers and coding standards.

---

.circleci/config.yml
.gitlab-ci.yml

**Do not merge this as-is.** 
Once the CI build passes:
1. The PR https://github.com/govCMS/govcms-ci/pull/3 needs to be merged
2. The image needs to be released to Quay.io (automated once merged)
3. This PR needs to be updated to remove `feature_updates` image label.
4. CI has to re-run again.
5. This PR only then can be merged.

Replaced CI runner image with govcms/govcms-ci.

---

.docker/images/govcms8/settings/settings.php

At the moment, there is no timeout for Redis, which means that Drupal will wait forever to Redis to become available. This can and has lead to site outages where Redis has been under immense load. 
Comprehensive testing done in https://github.com/amazeeio/drupal-example/pull/70#issuecomment-611589542

Add timeout to Redis connect

---

.docker/images/govcms8/settings/development.settings.php
.docker/images/govcms8/settings/production.settings.php

Simplifies the `environment_indicator` SaaS setup:
* Only differentiate between prod and non-prod
* Use WCAG AAA compliant colours

Updated environment indicator colours (AAA WCAG).

---

.docker/images/govcms8/scripts/govcms-deploy

- Drush 9 is included and incompatible with --database on sql-sync.

Remove --database option from sqlc-sync.

---

.docker/images/govcms8/settings/settings.php

Noting that this should be included with `scaffold-tooling`: https://github.com/govCMS/scaffold-tooling/commit/c17b59908d2d83df30a3cb6010dd0803c03bd92a
Including here for completeness and until follow-up cleanup ticket is actioned to remove redundant code from this repo.

Updated to non-deterministic hash salt.

---

.env.default

Release 8.9.6 will be tagged on this commit hash upon approval.
This release is only to include the changes to Drupal core in the GovCMS distribution.
Changes which have been merged into `develop` after release 8.9.3 are planned for inclusion in the next release which will come with the next distribution release.

Changes for release v8.9.6

---

.docker/Dockerfile.govcms8

As per https://github.com/govCMS/govcms-ci/blob/master/govcms-ci.Dockerfile#L39
Adds binaries required for pre-deploy validation scripts.

Added yq/jq binaries for pre-deploy validation scripts.

---

.docker/images/govcms8/settings/production.settings.php

- Adds the GOVCMS_FILE_TEMP_MAX_AGE environment variable to allow support agents to enable temporary file GC.

Enable GC override.

---

.docker/images/govcms8/settings/settings.php

The current default HTTP client timeout is 30 seconds which can be insufficient in some cases (e.g. importing external data using Migrate module).

[GOVCMSD8-765] Make the HTTP Client request timeout configurable.

---

.gitlab-ci.yml

- Ahoy push exports .env values which overrides any set by the CI runner process.
```
push:
usage: Push all docker images.
cmd: |
export $(grep -v '^#' .env.default | xargs)
. .docker/push.sh
```

[9.x]: Adds support for gitlab CI overrides.

---

.env.default

- Pin GovCMS version to 1.13.0 
- Pin  Drupal core to 8.9.11
- [GOVCMSD8-776]: Remove except schedules https://github.com/govCMS/govcms8lagoon/pull/189

Release 8.9.11

---

.gitlab-ci.yml

Switches CI to the internal docker registry.

[GOVCMS-5600] Use the internal docker registry.

---

.docker/images/nginx/helpers/200-no_robots_govcms_host.conf
.docker/images/nginx/tests/src/RobotsTxtTest.php
.gitlab-ci.yml

- Adds *.govcms.amazee.io to the ignore robots.txt regex
eg.
```
$ http https://nginx-ipaustralia-feature-ipa-dev.govcms.amazee.io/robots.txt
User-agent: *
Crawl-delay: 10
Disallow: /includes/
```
After change:
```
$ http https://nginx-ipaustralia-feature-ipa-dev.govcms.amazee.io/robots.txt
User-agent: *
Disallow: /
```

[GOVCMS-5619]: Add amazeeio domains to non-prod robots ignore.

---

.gitlab-ci.yml

Deploy to both legacy/new dockerhub namespaces.
During transitionary phase from the `govcms8lagoon` to `govcms` namespace this will ensure that the nightly gitlab run will:
* Build legacy image names (`govcms8lagoon/govcms8:edge`)
* Build modern image names (`govcms/govcms:edge-8.x`)
* Push to dockerhub
This aligns to the CI pipeline in the `9.x` branch which does the same for GovCMS9 images.

[GOVCMS-5035] Build both legacy/new container names.

---

tests/behat/behat.yml

Via @AlexSkrypnyk (https://medium.com/@alex.designworks/chromedriver-75-enforces-w3c-standard-breaking-behat-tests-460cad435545)

Fix behat tests; disable w3c protocol.

---

.env.default

- Create lean consolidated scaffold (D8/D9 SaaS, SaaS+, PaaS)
- The PHP version updated from 7.4.10 to 7.4.14
- Robots.txt for non-prod (nginx domains)
- Consolidate govcms lagoon images
- Move to new "uselagoon" namespace
- cURL error (60) SSL certificate problem
- Drupal core update from 8.9.11 to 8.9.13
- GovCMS8 distribution 8.x-1.14

8.9.12 release
