govCMS/lagoon

- .docker/images/govcms8/scripts/govcms-deploy
- .docker/images/govcms8/settings/settings.php
Requires base config management PR merged first:
https://projects.govcms.gov.au/GovCMS/govcms8-scaffold/merge_requests/2
> GOVCMS-552: Configuration import on deploy.

- .circleci/config.yml
> amazeeio-network check

- .docker/Dockerfile.govcms8
- .docker/images/govcms8/govcms.site.yml
- .docker/images/govcms8/scripts/govcms-deploy
Aligns with GovCMS7 Lagoon support for prod alias and sync in non-prod cloud environments on deploy.
https://github.com/govCMS/govcmslagoon/commit/f034014413593d165e7457eedd80e96ac967b809
> Templated drush alias for govcms-deploy script.

- .docker/images/nginx/helpers/expires.conf
matches 
https://github.com/govCMS/govcmslagoon/pull/55
and
https://github.com/govCMS/govcmslagoon/pull/57
> add BINARY_FILES_EXPIRES and set 1800s expiry

- tests/goss/goss.solr.yaml
> Add a test file for Solr testing

- .docker/Dockerfile.govcms8
- .docker/Dockerfile.mariadb-drupal
- .docker/Dockerfile.nginx-drupal
- .docker/Dockerfile.php
- .docker/Dockerfile.test
This is a placeholder pull request for the GovCMS8 1.0.0-beta2 security release
> Pin govcms8dev docker images to 1.0.0-beta2

- .env.default
Reverts govCMS/govcms8lagoon#35
> Revert "Update Drutiny to 7.x-3.x-beta2"

- .docker/Dockerfile.solr
JIRA: https://govdex.gov.au/jira/browse/GOVCMSD8-277
On-behalf-of: @salsadigitalauorg <sonny@salsadigital.com.au>
> [GOVCMSD8-277] Updated Solr config to load the correct contrib packages.

- .docker/images/govcms8/scripts/govcms-deploy
Related
https://github.com/govCMS/govcms8-scaffold-paas/pull/8
https://github.com/govCMS/govcms8-scaffold/pull/16
https://github.com/govCMS/govcms7-scaffold-paas/pull/2
https://github.com/govCMS/govcms7-scaffold/pull/11
https://github.com/govCMS/govcms8lagoon/pull/73
https://github.com/govCMS/govcmslagoon/pull/99
> GOVCMS-3718: Env testing

- .docker/Dockerfile.govcms8
- Removes python and adds a composer clearcache.
> [GOVCMSD8-420] Remove python from the image!

- .docker/images/test/drutiny
- .docker/scripts/lint-govcms
- .docker/scripts/phpunit
These tests are not being used, so low risk should be merged asap.
> [GOVCMSD8-423] Make APP_DIR consistent.

- .docker/images/govcms8/scripts/govcms-deploy
Re-roll of #81- this is to be merged after #84 and #85 to ensure a single character change to the 7.6.0 image
> [GOVCMS-3816] fixup incorrect drush alias call

- .docker/Dockerfile.nginx-drupal
- .docker/images/nginx/no_robots_govcms_host.conf
On-behalf-of: @salsadigitalauorg <sonny@salsadigital.com.au>
A new PR to merge into master instead of: https://github.com/govCMS/govcms8lagoon/pull/72
> Added robots.txt for *.govcms.gov.au domains.

- .docker/images/govcms8/settings/settings.php
Rerunning https://circleci.com/gh/govCMS/govcms8lagoon/402
> Added redis config for port and cache prefix.

- .docker/images/govcms8/settings/development.settings.php
- .docker/images/govcms8/settings/production.settings.php
- modules/lagoon/govcms_lagoon/govcms_lagoon.info.yml
* Display an Orange "Local Development" message on local docker - .*.docker.amazee.io
* Display an Orange "Branch Development" message on all non-master branches - .*(?<!master).govcms.amazee.io
* Display a Green "Edit Domain" message on edit domains - (?<!www).govcms.gov.au
* Display a Red "Public Domain" message on public domains - .*.gov.au
> Configure Environment indicator.

- README.md
This might help new devs not have to ask "why u no".
> [DOC ONLY] More information for the newly initiated.

- .env.default
Updates Lagoon images to latest released tag (`v1.2.0`)
> Updated Lagoon version.

- .docker/images/nginx/helpers/207-seucirty-headers.conf
- .docker/images/nginx/tests/src/SecurityHeadersTest.php
- Adds addtional security headers to nginx.﻿
> [GOVCMS-2677]: Nginx Security headers

- .docker/images/nginx/helpers/207-security-headers.conf
- .docker/images/nginx/tests/src/SecurityHeadersTest.php
Aligns env var with d7: https://github.com/govCMS/govcmslagoon/pull/141/files
> [GOVCMS-2677] Fixed typos.

- .docker/images/govcms8/settings/production.settings.php
Additional safety net - see GOVCMSD8-576 for full detail.
> Added override for temporary file deletion.

- .docker/images/govcms8/settings/settings.php
- composer.json
- modules/lagoon/lagoon_search/lagoon_search.info.yml
- modules/lagoon/lagoon_search/lagoon_search.install
- Adds hook_update to import configuration differences.
- Hard codes solr configuration overrides for lagoon_search.
*NB*: Update requires a cache clear afterwards for the configuration updates to be visible.
> Adds hook_update support for the solr changes.

- .circleci/config.yml
- .docker/Dockerfile.govcms8
- docker-compose.yml
Add the new variable GITHUB_TOKEN for the rate limit in Github.
```
composer config -g github-oauth.github.com ${GITHUB_TOKEN}
```
> Bump the rate limit in Github for CIrcleCI

- .gitlab-ci.yml
- Adds a CI stage for generating audit report.
> [GOVCMS-5205]: Execute the verify module stage.

- .docker/images/govcms8/scripts/govcms-deploy
Resolves CI/local issues with initial deploy
> Ensure theme extensions reset prior to bootstrap.

- .gitlab-ci.yml
- Allow deploy stages on schedule runs
- Add a deploy stage for the 9.x branch
> [GOVCMSD8-776]: Remove except schedules
